version: "3.8"

services:

  vite-docker:
    container_name: vite-app
    image: vite-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "./:/usr/src/app"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true